<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\Filament\AdminPanelProvider::class,
    App\Providers\Filament\CustomerPanelProvider::class,
    Webkul\Accounting\AccountingServiceProvider::class,
    Webkul\Account\AccountServiceProvider::class,
    Webkul\Analytic\AnalyticServiceProvider::class,
    Webkul\Blog\BlogServiceProvider::class,
    Webkul\Chatter\ChatterServiceProvider::class,
    Webkul\Contact\ContactServiceProvider::class,
    Webkul\Employee\EmployeeServiceProvider::class,
    Webkul\Field\FieldServiceProvider::class,
    Webkul\Inventory\InventoryServiceProvider::class,
    Webkul\Invoice\InvoiceServiceProvider::class,
    Webkul\Partner\PartnerServiceProvider::class,
    Webkul\Payment\PaymentServiceProvider::class,
    Webkul\Product\ProductServiceProvider::class,
    Webkul\Project\ProjectServiceProvider::class,
    Webkul\Purchase\PurchaseServiceProvider::class,
    Webkul\Recruitment\RecruitmentServiceProvider::class,
    Webkul\Sale\SaleServiceProvider::class,
    Webkul\Security\SecurityServiceProvider::class,
    Webkul\Support\SupportServiceProvider::class,
    Webkul\TableViews\TableViewsServiceProvider::class,
    Webkul\TimeOff\TimeOffServiceProvider::class,
    Webkul\FullCalendar\FullCalendarServiceProvider::class,
    Webkul\Timesheet\TimesheetServiceProvider::class,
    Webkul\Website\WebsiteServiceProvider::class,
    Webkul\PluginManager\PluginManagerServiceProvider::class,

    Cesa\Rekrutmen\RekrutmenServiceProvider::class,
    Cesa\Presensi\PresensiServiceProvider::class,
    Cesa\Payroll\PayrollServiceProvider::class,
];
